### PR TITLE
Implement rule-delimiter (#210)

### PR DESCRIPTION
**Pull request by tonyganch**
See #210.

@mrpavlikov, @kosteQ, @ognia, I've rebased [#302](https://github.com/csscomb/csscomb.js/pull/302) for you.
To push further changes you can either send PR's with commits to `mrpavlikov/210` branch or fetch this branch to your repo and open another PR to `dev` branch.

### CODE REVIEW

**Comment by cjaoude** [comment]
Umm, can we get this merged into the master already? much needed.

**Comment by paradox41** [comment]
@tonyganch What is left to be done with this PR? I am willing to finish it up if I can so we can get it merged in. Looking at the PR itself, looks like CSS, LESS and Sass are covered. Is it just a matter of fixing the mistakes? Documentation?

**Comment by tonyganch** [comment]
@paradox41, I'd like to understand how the option should work, because I find examples in test files confusing (they just don't correspond with discussion in #210).
So I'm interested in tests first (as a way of documenting and describing the feature) and then some code that makes those test pass.

**Comment by paradox41** [comment]
@tonyganch I finally have a chance to take a look at this and I want to ask a few questions before I start changing things:

1) There are a few stray files that don't look like they are following existing conventions (stray files in `test` when they should follow `{options-name}/test.js`. Am I correct? Should these be moved?
2) Are your line notes the only concerns you have? I have read through #210 but I want to ensure that my understanding of the spec is clear.

Thanks. Hopefully I'll be able to have this ready sometime tomorrow.

**Comment by tonyganch** [comment]
@paradox41, the biggest concern for me is documentation :) I want someone to write a bunch of (failing) tests, before and after, just to show how the feature should work. Because my understanding of the spec differs from what I see in this pr.
Tests should be placed in `{options-name}/test.js`, yes.
Maybe it'll make more sense to start a new branch from `dev` rather than modifying this one.

**Comment by paradox41** [comment]
Yeah, I like that idea.

**Pull request closed without merging**
