### PR TITLE
Update Travis badge

### PR DESCRIPTION
**Pull request by igncp**
Hi there,

Great project, and great change to adopt the ES6 in the dev branch. This PR is just to change the badge in the Readme.md, as the tests in the `dev` branch are not passing and it can be misleading.

Also, I saw another possible change in the `cli.js` file that I'll comment here if possible so I don't create a new issue. It is regarding the definition of the comb ( `var comb = new Comb();`), which could be done after getting the config, like: `var comb = new Comb(config);` without problems. The change would be considering the requirement of the options inside the `console.time()` monitoring, and thus increasing it slightly.  Would you consider this change as a PR?

### CODE REVIEW

**Comment by tonyganch** [comment]
Regarding Travis badge: I think it'll be misleading to show dev status for `master`.
And I don't know how to show a badge depending on a branch, all similar issues on Travis's tracker are closed as wontfixes, unfortunately.

Regarding changes in `cli.js`: yes, that would be nice. Thank you!

**Comment by tonyganch** [comment]
I've fixed tests for Travis, by the way: https://travis-ci.org/csscomb/csscomb.js/builds/67914501
Thank you for bringing my attention.
That does not fix broken cli though, there are just no tests for `cli.js` yet.

**Comment by igncp** [comment]
For the Travis badge, I made the PR to merge with the dev branch, I think that in that way when seeing the master branch Readme.md on GitHub you would see the same as now, but when switching to the dev branch you would see the badge of the dev branch. Anyway, maybe I am wrong, I'll propose the PR of the `cli.js` as soon as I can, thanks!

**Comment by tonyganch** [comment]
Yes, this would be cool, but I'm concerned about merging `dev` into `master` some time later.
We'll need either revert this commit or manually delete it from `master` branch, and this should be repeated on every merge.
I'm afraid I'll forget about it one day and dev-badge will go into `master`.
Maybe I don't see an easy way?

**Comment by igncp** [comment]
Ah ok, I see your point, that was my first thought before the PR, but I think the manual change in master would only be needed after the first merge. If you merge master with dev, change it manually on  master, commit and push, it will remain like that in the next merges if they don't contain changes in that line.

If you merge in the other direction, from master to dev, the change would be needed again, this time in dev, but if the merges are always in the same direction (from dev to master), it would only be needed the first time. Anyway, it requires to notice this in the first merge, possibly not soon, so maybe it is not the best.

**Pull request closed without merging**
